###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: ies-la-cierva-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=admin1234
        - MYSQL_DATABASE=testdb
        - MYSQL_USER=testuser
        - MYSQL_PASSWORD=admin1234
      ports:
        - "9202:3306"

    webserver:
      image: nginx:alpine
      container_name: ies-la-cierva-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "9200:80"


    phpmyadmin:
      depends_on:
        - mysql
      image: phpmyadmin/phpmyadmin
      restart: always
      ports:
        - '9283:80'
      environment:
        PMA_HOST: mysql
        MYSQL_ROOT_PASSWORD: admin1234


    php-fpm:
      build: phpdocker/php-fpm
      container_name: ies-la-cierva-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

      environment:
        - XDEBUG_CONFIG=client_host=${HOST_IP}
        - PHP_IDE_CONFIG=serverName=${XDEBUG_SERVERNAME}

    mailhog:
      image: mailhog/mailhog:latest
      container_name: ies-la-cierva-mailhog
      ports:
        - "9225:8025"

